project:
  type: book
  output-dir: docs

book:
  title: "ゼロから作るDeep Learning in R"
  author: "igjit"
  chapters:
    - index.qmd
    - ch02.qmd
    - ch03.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
